title: Kernel Creative Media
subtitle: make the web work for you
description: Kernel Creative Media is an integrated web and marketing firm with almost two decades of experience. We listen, collaborate and form customized solutions for you. Let us help grow your business and make it remarkable.

url: http://kernelcreativemedia.com
baseurl: ""
permalink: :title/

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: '#home'
 - title: About
   url: '#about'
 - title: Services
   url: '#services'
 - title: Portfolio
   url: '#portfolio'
 - title: Team
   url: '#team'
 - title: Contact
   url: '#contact'

social:
   github:
   twitter:
   facebook:

google_analytics: 'UA-15214456-1'

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'package.json']
