title: Kernel Creative Media
subtitle: make the web work for you
description: Kernel Creative Media offers custom web design & development that is SEO-optimized out of the box utilizing WordPress and Drupal content management systems.

url: http://kernelcreativemedia.com
baseurl: ""
permalink: :title/

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: '#home'
 - title: About
   url: '#about'
 - title: Services
   url: '#services'
 - title: Portfolio
   url: '#portfolio'
 - title: Team
   url: '#team'
 - title: Contact
   url: '#contact'

social:
   github: mattbanks
   twitter: mattbanks
   facebook: mattbanks

google_analytics: "XXXX"

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'package.json']
