baseURL = "https://www.kernelcreativemedia.com/"
languageCode = "en-us"
title = "Kernel Creative Media"
canonifyurls = true
theme = "kernelcreativemedia"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  tagline = "make the web work for you"
  MetaDescription = "Kernel Creative Media is an integrated web and marketing firm with almost two decades of experience. We listen, collaborate and form customized solutions for you. Let us help grow your business and make it remarkable."
  googleAnalyticsUserID = "UA-15214456-1"
  hideHUGOSupport = true
  CookieText = "This website uses cookies to ensure you get the best experience on our website."
  CookieLearnMore = "Learn more"
  CookieButtonText = "Got it!"

[[menu.main]]
  name = "Home"
  url = "#home"
  weight = -1
[[menu.main]]
  name = "About"
  url = "#about"
  weight = 1
[[menu.main]]
  name = "Services"
  url = "#services"
  weight = 2
[[menu.main]]
  name = "Portfolio"
  url = "#portfolio"
  weight = 3
[[menu.main]]
  name = "Team"
  url = "#team"
  weight = 4
[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 5
